//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XamarinNativeExamples.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XamarinNativeExamples.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste API Token here.
        /// </summary>
        public static string ApiKeyPlaceholder {
            get {
                return ResourceManager.GetString("ApiKeyPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles.
        /// </summary>
        public static string Articles {
            get {
                return ResourceManager.GetString("Articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearish.
        /// </summary>
        public static string Bearish {
            get {
                return ResourceManager.GetString("Bearish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bullish.
        /// </summary>
        public static string Bullish {
            get {
                return ResourceManager.GetString("Bullish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button click and long click.
        /// </summary>
        public static string ButtonClickHeader {
            get {
                return ResourceManager.GetString("ButtonClickHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable/disable button.
        /// </summary>
        public static string ButtonEnableHeader {
            get {
                return ResourceManager.GetString("ButtonEnableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button.
        /// </summary>
        public static string ButtonTitle {
            get {
                return ResourceManager.GetString("ButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Count:.
        /// </summary>
        public static string ClickCountLabel {
            get {
                return ResourceManager.GetString("ClickCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication.
        /// </summary>
        public static string ConnectivityHeader {
            get {
                return ResourceManager.GetString("ConnectivityHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XNE.
        /// </summary>
        public static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are unable to reach {0} at the moment. Please check your connection and try again..
        /// </summary>
        public static string HttpErrorMessage {
            get {
                return ResourceManager.GetString("HttpErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last week articles count: {0}.
        /// </summary>
        public static string LastWeekArticlesFormat {
            get {
                return ResourceManager.GetString("LastWeekArticlesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Click Count:.
        /// </summary>
        public static string LongClickCountLabel {
            get {
                return ResourceManager.GetString("LongClickCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutral.
        /// </summary>
        public static string Neutral {
            get {
                return ResourceManager.GetString("Neutral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got it!.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ooops!.
        /// </summary>
        public static string OoopsTitle {
            get {
                return ResourceManager.GetString("OoopsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping Count: {0}.
        /// </summary>
        public static string PingCountFormat {
            get {
                return ResourceManager.GetString("PingCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price: {0}.
        /// </summary>
        public static string PriceFormat {
            get {
                return ResourceManager.GetString("PriceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest service.
        /// </summary>
        public static string RestTitle {
            get {
                return ResourceManager.GetString("RestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Request.
        /// </summary>
        public static string SendRequest {
            get {
                return ResourceManager.GetString("SendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentiments:.
        /// </summary>
        public static string Sentiments {
            get {
                return ResourceManager.GetString("Sentiments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data received for ${0}. Please check if you have the correct stock symbol and try again..
        /// </summary>
        public static string StockEmptyErrorMessage {
            get {
                return ResourceManager.GetString("StockEmptyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock symbol:.
        /// </summary>
        public static string StockSymbol {
            get {
                return ResourceManager.GetString("StockSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StockSymbol: {0}.
        /// </summary>
        public static string StockSymbolFormat {
            get {
                return ResourceManager.GetString("StockSymbolFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. (AAPL, GOOGL etc).
        /// </summary>
        public static string StockSymbolHint {
            get {
                return ResourceManager.GetString("StockSymbolHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe.
        /// </summary>
        public static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below is a custom binding for implementing filter on your textbox using Regex. Try it the different examples below..
        /// </summary>
        public static string TextFilterDescription {
            get {
                return ResourceManager.GetString("TextFilterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtering text input.
        /// </summary>
        public static string TextFilterHeader {
            get {
                return ResourceManager.GetString("TextFilterHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower Case only.
        /// </summary>
        public static string TextFilterLowerCase {
            get {
                return ResourceManager.GetString("TextFilterLowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers only.
        /// </summary>
        public static string TextFilterNumber {
            get {
                return ResourceManager.GetString("TextFilterNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding Text property.
        /// </summary>
        public static string TextTextHeader {
            get {
                return ResourceManager.GetString("TextTextHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string TextTitle {
            get {
                return ResourceManager.GetString("TextTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time: {0:G}.
        /// </summary>
        public static string TimeFormat {
            get {
                return ResourceManager.GetString("TimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to https://finnhub.io/dashboard and copy the API Key..
        /// </summary>
        public static string TokenCopyMessage {
            get {
                return ResourceManager.GetString("TokenCopyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid  key. Please make sure the you paste the correct API Key from your dashboard..
        /// </summary>
        public static string TokenFailedMessage {
            get {
                return ResourceManager.GetString("TokenFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to https://finnhub.io/register and sign up..
        /// </summary>
        public static string TokenRegisterMessage {
            get {
                return ResourceManager.GetString("TokenRegisterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An API Key from finnhub.io is required to proceed with testing..
        /// </summary>
        public static string TokenStartMessage {
            get {
                return ResourceManager.GetString("TokenStartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key validated! Store the token on your device by pressing the Save button below..
        /// </summary>
        public static string TokenSuccessMessage {
            get {
                return ResourceManager.GetString("TokenSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste the API Key to the text box above then Test..
        /// </summary>
        public static string TokenTestMessage {
            get {
                return ResourceManager.GetString("TokenTestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try me!.
        /// </summary>
        public static string TryMe {
            get {
                return ResourceManager.GetString("TryMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something weird happened while requesting for data. Please try again..
        /// </summary>
        public static string UnknownErrorMessage {
            get {
                return ResourceManager.GetString("UnknownErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Interface.
        /// </summary>
        public static string UserInterfaceHeader {
            get {
                return ResourceManager.GetString("UserInterfaceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume: {0}.
        /// </summary>
        public static string VolumeFormat {
            get {
                return ResourceManager.GetString("VolumeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly articles count: {0}.
        /// </summary>
        public static string WeeklyArticlesFormat {
            get {
                return ResourceManager.GetString("WeeklyArticlesFormat", resourceCulture);
            }
        }
    }
}
